//! End to end with rr-hazards: its rates, scenarios and the fixture county records in
//! `crates/rr-hazards/tests/data` feed `assess` for all seven fixture households. Writes
//! `target/pipeline.md` (the targets users would see with today's hazard rates) and checks that
//! every output is well formed and deterministic.

use std::fmt::Write as _;

use rr_consequence::{CountyData, DURATION_BUCKETS, assess};
use rr_types::{BaseRate, BucketId, CountyRecord, LocationResolved, ReturnPeriod, Target};

#[derive(serde::Deserialize)]
struct Fixture {
    county: CountyRecord,
    location: LocationResolved,
}

const PAIRS: &[(&str, &str)] = &[
    ("chicago-student-zero-budget-1", "17031"),
    ("coos-bay-well-owner-2", "41011"),
    ("hays-kansas-farm-5", "20051"),
    ("miami-condo-retiree-1", "12086"),
    ("philadelphia-renters-4", "42101"),
    ("phoenix-apartment-cpap-1", "04013"),
    ("sugar-land-ev-household-3", "48157"),
];

const DATA: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../rr-hazards/tests/data");

fn cell(t: &Target) -> String {
    match *t {
        Target::Days { value, low, high } => {
            if value == 0.0 && high == 0.0 {
                "—".to_owned()
            } else {
                format!("{value} ({low}–{high})")
            }
        }
        Target::Months { value, low, high } => format!("{value} mo ({low}–{high})"),
        Target::Evacuate { p_need_10yr, .. } | Target::Readiness { p_need_10yr, .. } => {
            format!("{:.0} in 100", 100.0 * p_need_10yr)
        }
    }
}

#[test]
fn fixtures_end_to_end_with_rr_hazards() {
    let base_rates: Vec<BaseRate> = serde_json::from_str(
        &std::fs::read_to_string(format!("{DATA}/base_rates.json")).expect("base rates"),
    )
    .expect("base rates json");
    let mut md = String::from(
        "# End to end: rr-hazards → rr-consequence on the fixture households\n\n\
         Generated by `cargo test -p rr-consequence --test pipeline`, from rr-hazards' fixture \
         county records (`crates/rr-hazards/tests/data`). Each household at its own dial; \
         targets are ladder values with the 10th–90th percentile in brackets.\n",
    );
    for (name, fips) in PAIRS {
        let input = rr_types::fixtures::get(name).expect("fixture household");
        let fixture: Fixture = serde_json::from_str(
            &std::fs::read_to_string(format!("{DATA}/counties/{fips}.json")).expect("county"),
        )
        .expect("county json");
        let hz = rr_hazards::assess(&input, &fixture.county, &base_rates, &fixture.location);
        let county = CountyData::from_record(&fixture.county);
        let a = assess(&input, &hz.rates, county, &hz.scenarios);
        let again = assess(&input, &hz.rates, county, &hz.scenarios);
        assert_eq!(
            serde_json::to_string(&a.buckets).unwrap(),
            serde_json::to_string(&again.buckets).unwrap(),
            "{name}: not deterministic"
        );
        assert_eq!(a.buckets.len(), 14);
        for b in &a.buckets {
            assert!(!b.frequency_sentences.is_empty(), "{name} {}", b.id);
            if let Target::Days { value, low, high } = b.target {
                assert!(low <= value && value <= high, "{name} {}", b.id);
            }
        }
        let _ = writeln!(
            md,
            "\n## {name} ({}, {}) — dial `{}`\n",
            fixture.county.name, fixture.county.state_abbr, input.dials.return_period
        );
        let mut rates: Vec<_> = hz
            .rates
            .iter()
            .filter(|r| r.rate_per_year >= 0.005)
            .collect();
        rates.sort_by(|a, b| b.rate_per_year.total_cmp(&a.rate_per_year));
        let listed: Vec<String> = rates
            .iter()
            .map(|r| format!("{} {:.3}", r.hazard, r.rate_per_year))
            .chain(
                hz.scenarios
                    .iter()
                    .map(|s| format!("scenario {} {:.4}", s.id, s.rate_per_year)),
            )
            .collect();
        let _ = writeln!(
            md,
            "rr-hazards' household event rates (a year, 0.005 and above): {}\n",
            listed.join(", ")
        );
        let _ = writeln!(
            md,
            "| Bucket | Target | Top drivers of the target |\n|---|---|---|"
        );
        for b in &a.buckets {
            let top: Vec<String> = b
                .contributions
                .iter()
                .take(3)
                .map(|c| format!("{} {:.0} %", c.hazard, 100.0 * c.share))
                .collect();
            let _ = writeln!(
                md,
                "| {} | {} | {} |",
                b.id,
                cell(&b.target),
                top.join(", ")
            );
        }
        let at_default: Vec<String> = ReturnPeriod::ALL
            .iter()
            .map(|rp| {
                let mut p = input.clone();
                p.dials.return_period = *rp;
                let x = assess(&p, &hz.rates, county, &hz.scenarios);
                let d: Vec<String> = DURATION_BUCKETS
                    .iter()
                    .chain([BucketId::Income].iter())
                    .map(|b| match x.bucket(*b).target {
                        Target::Days { value, .. } | Target::Months { value, .. } => {
                            format!("{value}")
                        }
                        _ => String::new(),
                    })
                    .collect();
                format!("| {rp} | {} |", d.join(" | "))
            })
            .collect();
        let _ = writeln!(
            md,
            "\nBy dial (days; income in months):\n\n| Dial | power | boil | no water | supplies | thermal | medicine | comms | income |\n|---|---|---|---|---|---|---|---|---|\n{}",
            at_default.join("\n")
        );
        for w in &a.warnings {
            let _ = writeln!(md, "\n- Warning ({}): {} {}", w.id, w.message, w.why);
        }
        for s in &a.scenarios {
            let _ = writeln!(
                md,
                "- Scenario {} ({}): {}",
                s.id,
                if s.on { "on" } else { "off" },
                s.effect_summary
            );
        }
        for n in &a.notes {
            let _ = writeln!(md, "- Note: {n}");
        }
        let _ = writeln!(md, "\nStatement:\n");
        for s in &a.statement {
            let _ = writeln!(md, "> {s}");
        }
    }
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../target/pipeline.md");
    std::fs::write(path, md).expect("write target/pipeline.md");
}
