//! Writes `target/supply-report.md`: every requirement line for the Philadelphia and Coos Bay
//! fixtures at their research targets, for the planner and the owner to read. The test also pins
//! the headline totals so the report cannot drift silently.

mod common;

use std::fmt::Write as _;

use rr_supply::{LineKind, SupplyContext, sized_requirements, tier_recommended};
use rr_types::{BucketAssessment, Target, fixtures};

fn target_words(b: &BucketAssessment) -> String {
    match b.target {
        Target::Days { value, .. } => format!("{value} days"),
        Target::Months { value, .. } => format!("{value} months"),
        Target::Evacuate {
            p_need_10yr,
            notice_hours_low,
            notice_hours_high,
            days_away,
        } => format!(
            "leave: {:.0}% in 10 years, {notice_hours_low}–{notice_hours_high} h warning, {days_away} days away",
            p_need_10yr * 100.0
        ),
        Target::Readiness { p_need_10yr, .. } => {
            format!("readiness: {:.0}% in 10 years", p_need_10yr * 100.0)
        }
    }
}

fn section(out: &mut String, name: &str, ctx: &SupplyContext) {
    let input = fixtures::get(name).unwrap();
    let targets = common::targets_for(name);
    let lines = sized_requirements(&input, &targets, ctx);
    let _ = writeln!(out, "## {name}\n");
    let _ = writeln!(
        out,
        "Targets: {}.\n",
        targets
            .iter()
            .map(|b| format!("{} {}", b.id, target_words(b)))
            .collect::<Vec<_>>()
            .join("; ")
    );
    let _ = writeln!(out, "Tier recommended: {}.\n", tier_recommended(&targets));
    let _ = writeln!(
        out,
        "| line | kind | tier | quantity | unit | estimate | plain |\n| --- | --- | --- | --- | --- | --- | --- |"
    );
    for l in &lines {
        let kind = match l.kind {
            LineKind::Need => "need",
            LineKind::Alternative => "alternative",
            LineKind::Optional => "optional",
            LineKind::Note => "note",
        };
        let _ = writeln!(
            out,
            "| `{}` | {kind} | {} | {} | {} | {} | {} |",
            l.line.id,
            l.tier,
            l.line.quantity,
            l.line.unit,
            if l.prior { "yes" } else { "" },
            l.line.plain.replace('|', "/")
        );
    }
    let _ = writeln!(out);
}

#[test]
fn write_the_fixture_report() {
    let mut out = String::from(
        "# Supply requirements for the reference households\n\nGenerated by `cargo test -p rr-supply --test report`. Targets are the research values at the default dial (docs/research/risk-model.md §3.8).\n\n",
    );
    section(
        &mut out,
        "philadelphia-renters-4",
        &SupplyContext {
            days_at_or_above_95f: Some(3.3),
            latitude: Some(39.95),
        },
    );
    section(
        &mut out,
        "coos-bay-well-owner-2",
        &SupplyContext {
            days_at_or_above_95f: Some(0.0),
            latitude: Some(43.37),
        },
    );
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../target/supply-report.md");
    std::fs::write(path, &out).expect("write target/supply-report.md");
    assert!(out.contains("`water_out.water_gallons` | need | h72 | 12.9 | gallon"));
    assert!(out.contains("`water_out.water_gallons` | need | w2 | 37.6 | gallon"));
    assert!(out.contains("`water_out.water_treatment_capacity` | need | m3 | 96.8 | gallon"));
}
