//! Worked example: the Philadelphia fixture household with stub curves built from the research
//! prototype's parameters (research risk-model §8). Writes `target/budget-example.md` for the
//! planner and checks the numbers the research states.

mod common;

use std::fmt::Write as _;
use std::path::PathBuf;

use common::philadelphia::{self, DIAL_RATE};
use common::{audit, days_at};
use rr_budget::{BudgetInput, BudgetOptions, BudgetResult, GuardrailContext, allocate};
use rr_types::{BucketId, PlanItemKind, TierId, fixtures};

fn run() -> (rr_types::PlanInput, BudgetResult) {
    let household = fixtures::get("philadelphia-renters-4").unwrap();
    let (items, meta) = philadelphia::catalogue();
    let risks = philadelphia::risks();
    let context = GuardrailContext::default();
    let input = BudgetInput {
        household: &household,
        catalogue: &items,
        meta: &meta,
        requirements: &[],
        risks: &risks,
        context: &context,
        options: BudgetOptions::default(),
    };
    let result = allocate(&input).expect("allocates");
    (household, result)
}

fn money(x: f32) -> String {
    if x == 0.0 {
        "free".into()
    } else {
        format!("${:.0}", x)
    }
}

/// The first few words of an item name, for the comparison table.
fn short(name: &str) -> String {
    let head = name.split([':', '(', ';']).next().unwrap_or(name).trim();
    head.to_owned()
}

fn example_markdown(result: &BudgetResult) -> String {
    let risks = philadelphia::risks();
    let mut md = String::new();
    let _ = writeln!(md, "# rr-budget worked example: Philadelphia renters\n");
    let _ = writeln!(
        md,
        "Generated by `cargo test -p rr-budget --test philadelphia`. Household: fixture \
         `philadelphia-renters-4` (two adults, a 6-year-old and a 70-year-old on daily medicine; \
         renting a rowhouse; $60 a month, no one-off money; half a month of expenses saved).\n"
    );
    let _ = writeln!(
        md,
        "Inputs are stubs until `rr-plan` wires the real crates: curves tabulated from the research \
         prototype's parameters (research risk-model §8, `rm_proto/params.py`) at the research's \
         default dial (Λ ≤ {DIAL_RATE:.4} a year, \"about 1 in 100\"); prices from research §8.6 \
         (illustrative); hazard shares read off the prototype's event list.\n"
    );
    let _ = writeln!(md, "## Targets and coverage (days)\n");
    let _ = writeln!(
        md,
        "| Bucket | Target | After month 0 | After month 6 | End of plan |"
    );
    let _ = writeln!(md, "| --- | ---: | ---: | ---: | ---: |");
    for (b, c) in &risks.curves {
        let end = result.coverage_by_month.len() - 1;
        let _ = writeln!(
            md,
            "| {} | {} | {:.1} | {:.1} | {:.1} |",
            b.name(),
            c.target_days,
            days_at(result, 0)[b],
            days_at(result, 6)[b],
            days_at(result, end)[b],
        );
    }
    let _ = writeln!(md);
    for month in result.plan.months.iter().take(7) {
        let spent: f32 = month
            .items
            .iter()
            .filter(|i| !i.done && i.kind != PlanItemKind::FreeAction)
            .map(|i| i.est_cost_usd)
            .sum::<f32>()
            + 0.0;
        let _ = writeln!(
            md,
            "## Month {}: ${:.0} in, ${:.0} used\n",
            month.index, month.budget_usd, spent
        );
        let _ = writeln!(md, "| Step | Qty | Cost | Tier | Why |");
        let _ = writeln!(md, "| --- | ---: | ---: | --- | --- |");
        for it in &month.items {
            let kind = match it.kind {
                PlanItemKind::FreeAction => "free",
                PlanItemKind::Purchase => "buy",
                PlanItemKind::Reserve => "save",
            };
            let _ = writeln!(
                md,
                "| {} ({kind}) | {} {} | {} | {} | {} |",
                it.name,
                it.quantity,
                it.unit,
                money(it.est_cost_usd),
                it.tier.name(),
                it.why
            );
        }
        let _ = writeln!(md);
    }
    let _ = writeln!(md, "## After month 6\n");
    for month in result.plan.months.iter().skip(7) {
        let lines: Vec<String> = month
            .items
            .iter()
            .map(|i| format!("{} ({})", i.name, money(i.est_cost_usd)))
            .collect();
        let _ = writeln!(md, "- Month {}: {}", month.index, lines.join("; "));
    }
    let _ = writeln!(md);
    match result.plan.done_month {
        Some(m) => {
            let _ = writeln!(md, "Every bucket reaches its target by **month {m}**.\n");
        }
        None => {
            let _ = writeln!(md, "The plan does not reach every target.\n");
        }
    }
    let _ = writeln!(
        md,
        "Tier reached with what the household has now: {}. At the end of the plan: {}. Recommended: {}.\n",
        result.tier_reached.name(),
        result.tier_at_plan_end.name(),
        result.tier_recommended.name()
    );
    if !result.plan.envelopes.is_empty() {
        let _ = writeln!(md, "Sinking funds:\n");
        for e in &result.plan.envelopes {
            let _ = writeln!(
                md,
                "- {}: ${:.0} saved of ${:.0}",
                e.item_id, e.saved_usd, e.needed_usd
            );
        }
        let _ = writeln!(md);
    }
    if let Some(s) = &result.plan.savings_track {
        let _ = writeln!(
            md,
            "Savings track: {} months of expenses (${:.0}); {} months saved now; suggested ${:.0} a month. {}\n",
            s.target_months, s.target_usd, s.current_months, s.monthly_suggestion_usd, s.why
        );
    }
    let _ = writeln!(md, "## Compared with research risk-model §8.6\n");
    let _ = writeln!(md, "| Month | Research prototype | This crate |");
    let _ = writeln!(md, "| --- | --- | --- |");
    let research = [
        "Free steps (plan, documents, alerts, reused bottles, water heater, refill rule, heat plan, alarms, neighbours, half tank, insurance check)",
        "Medicine cushion $10; 3 days of food $30",
        "First-aid kit $30; lights $35",
        "Battery fans $30; power bank $25",
        "Food to 7 days $40; blankets $40",
        "Two 5-gallon water containers $35",
        "Get-home bag $40; go-bag $30",
    ];
    for (m, r) in research.iter().enumerate() {
        let ours: Vec<String> = result
            .plan
            .months
            .get(m)
            .map(|month| {
                if m == 0 {
                    vec![format!("{} free steps", month.items.len())]
                } else {
                    month
                        .items
                        .iter()
                        .map(|i| format!("{} {}", short(&i.name), money(i.est_cost_usd)))
                        .collect()
                }
            })
            .unwrap_or_default();
        let _ = writeln!(md, "| {m} | {r} | {} |", ours.join("; "));
    }
    let _ = writeln!(
        md,
        "\nWhy they differ: DESIGN §4.7 orders life-safety items first and `docs/ENGINE-API.md` \
         lists water as life-safety, so the water containers move from month 5 to month 1 (the \
         prototype had no life-safety flags). Food is bought in day-ladder chunks (to 2, 3, 5, 7 \
         and 10 days) instead of the prototype's hand-made 3-, 7- and 14-day bundles, and heat \
         and cold are two parts of one bucket instead of two buckets. Months 1 to 6 spend the \
         same $345 of $360 in both.\n"
    );
    let _ = writeln!(md, "Warnings:\n");
    for w in &result.warnings {
        let _ = writeln!(md, "- `{}` ({}): {} {}", w.id, w.severity, w.message, w.why);
    }
    if result.warnings.is_empty() {
        let _ = writeln!(md, "- none");
    }
    let _ = writeln!(md);
    let _ = writeln!(
        md,
        "Left out: {} (specialised rare-catastrophe items get $0 unless the household opts in).",
        result
            .rare_catastrophic_skipped
            .iter()
            .map(|i| i.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    );
    md
}

fn target_dir() -> PathBuf {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    std::env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| manifest.join("../../target"))
}

fn month_of(result: &BudgetResult, id: &str) -> Option<u16> {
    result
        .sequence
        .iter()
        .find(|p| p.item_id == id)
        .map(|p| p.month)
}

#[test]
fn writes_the_worked_example() {
    let (_, result) = run();
    let md = example_markdown(&result);
    let dir = target_dir();
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::write(dir.join("budget-example.md"), &md).unwrap();

    // Month 0 is free steps only (no one-off money), and includes the research's month-0 list.
    let m0 = &result.plan.months[0];
    assert!(m0.items.iter().all(|i| i.kind == PlanItemKind::FreeAction));
    for id in [
        "documents_copied",
        "water_reused_bottles",
        "alarm_test",
        "medication_refill_rule",
    ] {
        assert!(m0.items.iter().any(|i| i.item_id == id), "{id} in month 0");
    }
    // Research §8.6: the free steps "alone cover ~2.5 of the 3 water days and 7 medicine days".
    let after0 = days_at(&result, 0);
    assert!((after0[&BucketId::WaterOut] - 2.5).abs() < 1e-9);
    assert!((after0[&BucketId::Medication] - 7.0).abs() < 1e-9);

    // Money never runs out, and months 1-6 use at most 6 x $60.
    let (left, lives) = audit(&result.plan);
    assert!(
        left.iter().all(|&x| x > -0.05),
        "money never negative: {left:?}"
    );
    let spent_1_to_6: f32 = result.plan.months[1..=6]
        .iter()
        .flat_map(|m| m.items.iter())
        .filter(|i| i.kind == PlanItemKind::Purchase)
        .map(|i| i.est_cost_usd)
        .sum();
    assert!(spent_1_to_6 <= 360.0 + 0.01, "{spent_1_to_6}");

    // The research's three-day and get-home purchases all land in the first six months.
    for id in [
        "water_containers",
        "lights",
        "first_aid_kit",
        "battery_fans",
        "power_bank",
        "blankets",
        "get_home_bag",
        "medicine_cushion",
    ] {
        let m = month_of(&result, id).unwrap_or(99);
        assert!((1..=6).contains(&m), "{id} bought in month {m}");
    }
    // The extra medicine is the research's example of promotion: a two-week item bought during
    // the three-day tier because it is at least five times better value per dollar.
    let cushion = result
        .sequence
        .iter()
        .find(|p| p.item_id == "medicine_cushion")
        .unwrap();
    assert!(cushion.promoted);
    assert_eq!(cushion.tier, TierId::W2);
    // Upgrades with nothing left to cover are never bought; rare-catastrophe items get $0.
    for id in ["power_station", "more_water_containers", "weather_radio"] {
        assert_eq!(month_of(&result, id), None, "{id}");
    }
    assert_eq!(result.rare_catastrophic_skipped, ["radiation_meter"]);
    // Research §8.6: after months 7-12 "supply targets are met".
    let done = result.plan.done_month.expect("reaches every target");
    assert!(done <= 12, "done in month {done}");
    assert_eq!(result.tier_recommended, TierId::W2);
    assert_eq!(result.tier_at_plan_end, TierId::W2);
    // The one sinking fund (the $100 cash reserve) resolves within ceil(100 / 60) = 2 months.
    assert_eq!(lives.len(), 1);
    assert_eq!(lives[0].item_id, "cash_reserve");
    assert!(lives[0].bought.unwrap() - lives[0].opened <= 2);
    // Income: 4 months of $4,200 on the savings track, fed by the $60 once supplies are done.
    let s = result.plan.savings_track.as_ref().unwrap();
    assert_eq!(
        (
            s.target_months,
            s.target_usd,
            s.current_months,
            s.monthly_suggestion_usd
        ),
        (4.0, 16_800.0, 0.5, 60.0)
    );
    assert!(result.warnings.is_empty(), "{:?}", result.warnings);
    // Every purchase explains itself with a goal and a natural frequency.
    for it in result.plan.months.iter().flat_map(|m| m.items.iter()) {
        assert!(!it.why.is_empty() && !it.why.contains("NaN"), "{}", it.why);
        if it.kind == PlanItemKind::Purchase {
            assert!(
                it.why.contains("of 100 households") || it.why.contains("Nearly all"),
                "{}",
                it.why
            );
        }
    }
}

/// Research risk-model §3.2: "For Philadelphia water, the first 3 days of storage cover about 60x
/// more expected disruption-days than days 30-33 ... for food about 190x". The integral of the
/// tabulated stub curves reproduces both. (The same passage says about 1,600x for power; the
/// prototype's published parameters give about 720x, so the figure in the text looks stale.)
#[test]
fn first_three_days_versus_days_30_to_33() {
    let r = philadelphia::risks();
    let ratio = |b: BucketId| {
        let c = &r.curves[&b];
        c.integral(0.0, 3.0) / c.integral(30.0, 33.0)
    };
    let water = ratio(BucketId::WaterOut);
    let food = ratio(BucketId::Supplies);
    let power = ratio(BucketId::Power);
    assert!((water / 60.0 - 1.0).abs() < 0.10, "water {water}");
    assert!((food / 190.0 - 1.0).abs() < 0.10, "food {food}");
    assert!((power / 718.0 - 1.0).abs() < 0.05, "power {power}");
}

/// The stub curves reproduce research risk-model §3.8's default-dial targets (power 2.8 d, water
/// 2.8 d, boil notice 4 d, food 9.6 d, medicine 12 d, heat or cold 1.7 d, communications 1.4 d),
/// and the tabulated curve integrates like the exact lognormal mixture.
#[test]
fn stub_curves_match_research_section_3_8() {
    use common::{lambda_exact, raw_target};
    let cases = [
        (BucketId::Power, philadelphia::power(), 2.8),
        (BucketId::WaterOut, philadelphia::water_out(), 2.8),
        (BucketId::WaterBoil, philadelphia::water_boil(), 4.0),
        (BucketId::Supplies, philadelphia::supplies(), 9.6),
        (BucketId::Medication, philadelphia::medication(), 12.2),
        (BucketId::Thermal, philadelphia::thermal(), 1.7),
        (BucketId::Comms, philadelphia::comms(), 1.4),
    ];
    let r = philadelphia::risks();
    for (bucket, events, want) in cases {
        let got = raw_target(&events, DIAL_RATE);
        assert!((got - want).abs() < 0.06, "{bucket}: {got} vs {want}");
        // Exact integral of the mixture by fine trapezoids versus the table's closed form.
        let (a, b) = (0.25, 21.0);
        let n = 20_000;
        let mut exact = 0.0;
        for i in 0..n {
            let t0 = a + (b - a) * f64::from(i) / f64::from(n);
            let t1 = a + (b - a) * f64::from(i + 1) / f64::from(n);
            exact += 0.5 * (lambda_exact(&events, t0) + lambda_exact(&events, t1)) * (t1 - t0);
        }
        let table = r.curves[&bucket].integral(a, b);
        assert!(
            (table / exact - 1.0).abs() < 0.005,
            "{bucket}: {table} vs {exact}"
        );
    }
    // At exactly one-in-100 the water target is 3.003 days, one hair over the ladder's 3.
    assert!(raw_target(&philadelphia::water_out(), 0.01) > 3.0);
}
