[package]
name = "rr-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Ready Reckoner: wasm"

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
